---
title: "Research"
output: html_document
---

My research interests are in several different areas in Statistics. My main focus is on Robust Statistics & Bootstrapping. It can be extremely difficult to find the outliers in a multivariate setting and outliers can ruin the analysis. This led to research about Robust Multivariate Regression, Robust Discriminant Analysis and the one way MANOVA test. Bootstrap tests can be used to weaken assumptions such as a common covariance matrix. I am also interested in statistical learning (also known as machine learning).

## Grants

* CAS Research/Proposal Development Summer Grant (Received)
* Chancellor's Innovation Scholars Program (Applied)
* NSF --- Statistics--PD 18-1269 (Not funded, received good reviews)
* NSF --- HDR DSC: The Civically-Engaged Data Science Co-op (Not funded, received good reviews)
* NSF --- HDR DSC: Pipeline for Environmental Data Science (PEDS) (Not funded, received good reviews)


## Publications 

* "Large Sample Bootstrap Prediction Intervals for Variable Selection or Shrinkage Estimators", Udder Revisions, with Lasanthi Watagoda

* "[HRLR Regression](https://www.tandfonline.com/doi/full/10.1080/27658449.2021.1921904)"  RMS: Research in Mathematics & Statistics, with Alan Arnholt, Lasanthi Watagoda. 

* "[Advertisement for Predictive Model Building,](https://stat-ata-asu.github.io/PredictiveModelBuilding/index.html)" Conference Proceedings,  $32^{nd}$ Annual International Conference on Technology in Collegiate Mathematics (ICTCM), with Alan Arnholt, Lasanthi Watagoda

* "[An Approximation to the Skew--Normal Distribution,](http://www.m-hikari.com/imf/imf-2019/5-8-2019/p/rupasingheIMF5-8-2019.pdf)"  Vol. 14, 2019, no. 7, 253-261, International Mathematical Forum, with Joel Sanqui, Lasanthi Watagoda. 

* "[Examining the $n \geq 30$ is Sufficiently Large Caveat for the Sampling Distribution of $\bar{X}$ to Follow a Normal Distribution,](http://www.seio.es/BBEIO/BEIOVol34Num3/files/assets/basic-html/page-16.html)" Bulletin of Statistics and Operations Research, with Alan Arnholt, William Bauldry and Lasanthi Watagoda.

* "[Sprint Assessment using Machine Learning and a Wearable Accelerometer,](https://www.ncbi.nlm.nih.gov/pubmed/30676153)", Journal of Applied Biomechanics, with Reed D. Gurchiek, Lasanthi Watagoda, Ryan S. McGinnis, Alan Arnholt, Herman van Werkhoven, Alan Needle, Jeffrey M. McBride. 


* "[Bootstrapping analogs of the One-Way MANOVA test,](https://www.tandfonline.com/doi/full/10.1080/03610926.2018.1515363)", Communication in Statistics Theory and Methods, with David J Olive. 

* "[A Relationship Between One-Way MANOVA Test Statistic and the Hotelling Lawley Trace Test Statistic,](http://www.ccsenet.org/journal/index.php/ijsp/article/view/0/37171)" Vol. 7, No. 6, 2018, International Journal of Statistics and Probability.

* "[Bootstrapping analogs of the Hotelling's $T^2$ test,](http://www.tandfonline.com/doi/abs/10.1080/03610926.2017.1337146?journalCode=lsta20)"  Communications in Statistics Theory and Methods, Oct. 17, 2017 with Lasanthi Watagoda.

* "[Visualizing and Testing the Multivariate Linear Regression Model,](http://www.ccsenet.org/journal/index.php/ijsp/article/view/43460)" International Journal of Statistics and Probability, January 22, 2015, with David J Olive, Lasanthi Watagoda.









## Conference talks


* ICTCM, "A Unified Introduction to Predictive Model Building for Undergraduate Researchers", July 2020, Contributed Talk

* Joint Mathematics Meetings, "A new regularization and variable selection technique - HRLR", January 2019, Contributed Talk

* Joint Mathematics Meetings, "Bootstrapping analogs of the one way MANOVA test", January 2018, Contributed Talk

* Statistics Group Meeting, "Introduction to Overleaf: A collaborative real time LaTeX writing tool", October 2017, Contributed Talk

* A Workshop in Developing Effective Learning Practices --- Appalachian State University, September 2017, Attended

* Datarobot Workshop in Machine Learning --- Appalachian State University, August 2017, Attended

* Southern Illinois University, "Bootstrapping analogs of the one way MANOVA test", April 2017, Invited Talk [Presentation Slides](http://lagrange.math.siu.edu/Olive/sHTalk.pdf)

* Joint Mathematics Meetings, "Bootstrapping analogs of the Hotteling's $T^2$ test", January 2017, Contributed Talk

* Appalachian State University, "Teaching Statistical Inference", November 2016, Invited Talk

* Appalachian State University, "Bootstrapping analogs of the Hotteling's $T^2$ test", November 2016, Contributed Talk

* Women in Statistics \& Data Science, October 2016, Attended

* SIAM Central States Section, "Bootstrapping analogs of the Hotteling's $T^2$ test", October 2016, Contributed Talk

* Lloyd Roeling UL Lafayette Conference: Statistics, "Bootstrapping analogs of the Hotteling's $T^2$ test", November 2015, Contributed Talk

* International Conference on Robust Rank-Based and Nonparametric Methods, Western Michigan University, "Visualizing and Testing the Multivariate Linear Regression Model", April 2015, Poster Presentation

* Presented a poster at Southern Illinois University, Graduate Research Conference, "Visualizing and Testing the Multivariate Linear Regression Model", April 2015, Poster Presentation




* * *